version: "3.7"
services:
  db:
    image: mysql:5.7
    container_name: my-db
    networks:
      - my-db-bridge
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
  mp-rbac-db:
    image: flyway/flyway:6.5
    container_name: demodb
    networks:
      - mp-db-bridge
    command: -url=jdbc:mysql://db -schemas=mp_rbac -user=root -password=123456 -connectRetries=60 migrate
    volumes:
      - ./rbac:/flyway/sql
    depends_on:
      - db
networks:
  mp-db-bridge:
    name: my-db
    ipam:
      driver: default
