version: '3.1'

services:

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    # - MYSQL_DATABASE=db_test
    # - MYSQL_USER=test
    # - MYSQL_PASSWORD=testPassword

  migrate:
    image: flyway:6.5-alpine-ci
    # command: ["/flyway/flyway", "migrate"]
    command: ["./ciTest.sh"]
    user: flyway
    volumes:
    - ".:/code"
    working_dir: /code
    environment:
      FLYWAY_DRIVER: com.mysql.cj.jdbc.Driver
      # FLYWAY_URL: jdbc:mysql://mysql:3306/db_test?useUnicode=true
      FLYWAY_DB_HOST: mysql
      FLYWAY_USER: root
      FLYWAY_PASSWORD: 123456
      FLYWAY_CONNECT_RETRIES: 1
    depends_on:
      - mysql